services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dist:/var/lib/grafana/plugins/compunnel-custommetrics-datasource
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_USERS_ALLOW_SIGN_UP=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped